---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: 'My Apps'
subtitle: 'Pohle'
#logo: "logo.png"
#icon: "fas fa-skull-crossbones" # Optional icon

header: false
footer: false

defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items: 
      - name: GitLab
        logo: assets/icons/gitlab.png
        url: https://gitlab.pohle-gz.de
        target: "_blank"
      - name: Kibana
        logo: assets/icons/kibana.svg
        url: https://kibana.pohle-gz.de
        target: "_blank"
      - name: Monitoring
        logo: assets/icons/icinga2.svg
        url: https://monitoring.pohle-gz.de/icingaweb2
        target: "_blank"
      - name: Passwords
        logo: assets/icons/vault.png
        url: https://vault.003.apps.pohle-gz.de
        target: "_blank"

  - name: Nextcloud
    icon: "fas fa-cloud"
    items:
      - name: Nextcloud 002
        logo: assets/icons/nextcloud.svg
        url: https://nc.002.apps.pohle-gz.de
        target: "_blank"
      - name: Nextcloud 003
        logo: assets/icons/nextcloud.svg
        url: https://nc.003.apps.pohle-gz.de
        target: "_blank"

  - name: Plex
    icon: "fas fa-cloud"
    items:
      - name: Plex 002
        logo: assets/icons/plex.png
        url: https://plex.002.apps.pohle-gz.de
        target: "_blank"
      - name: Plex 003
        logo: assets/icons/plex.png
        url: https://plex.003.apps.pohle-gz.de
        target: "_blank"
